repos = [
    "dhth/act3",
    "dhth/bmm",
    "dhth/chronotes",
    "dhth/commits",
    "dhth/cueitup",
    "dhth/dstll",
    "dhth/ecscope",
    "dhth/ecsv",
    "dhth/ghx",
    "dhth/hours",
    "dhth/kplay",
    "dhth/mrj",
    "dhth/mult",
    "dhth/omm",
    "dhth/outtasync",
    "dhth/prs",
    "dhth/punchout",
    "dhth/schemas",
    "dhth/shfl",
    "dhth/squidge",
    "dhth/squish",
    "dhth/tash",
    "dhth/tbll",
    "dhth/tomo",
    "dhth/urll",
]
trusted_authors = ["dependabot[bot]", "github-actions[bot]"]
base_branch = "main"
head_pattern = "(dependabot|update)"
merge_type = "squash"
