name: audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2,6'

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
