name: dry-run

on:
  workflow_dispatch:

jobs:
  dry-run:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Dry run
        uses: ./.github/actions/dry-run
        with:
          mrj_app_id: ${{ secrets.MRJ_APP_ID }}
          mrj_app_private_key: ${{ secrets.MRJ_APP_PRIVATE_KEY }}
