name: release-check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "*Cargo.*"
      - "**/*.rs"
      - ".goreleaser.yaml"
      - ".github/workflows/release-check.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release check
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check

  publish-crates-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --dry-run
