name: release-check

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".goreleaser.yaml"
      - ".github/workflows/release-check.yml"
  pull_request:
    paths:
      - ".goreleaser.yaml"
      - ".github/workflows/release-check.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release check
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check

  publish-crates-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --dry-run
